### ISSUE TITLE
Proposal to increase fnv version so its dependency 'hexate' is no longer used (elixir 1.15 issue)

### ISSUE THREAD

**Issue by seungjinstord** [stordco/data-streams-ex#20]
https://hex.pm/packages/fnv
is not actively under development, and its dependency - [hexate](https://hex.pm/packages/hexate) isn't either.

The key issue is hexate. It has been creating issues for elixir 1.15 when testing compilation:

```
===> Compilation failed: there is no code in this directory (/myapp/_build/dev/lib/hexate), it is unreadable or for some other reason is not a recognizable application structure.
==> myapp
** (Mix) Could not compile dependency :hexate, ".../.asdf/installs/elixir/1.15.4-otp-25/.mix/elixir/1-15/rebar3 bare compile --paths /myapp/_build/dev/lib/*/ebin" command failed. 
Errors may have been logged above. 
You can recompile this dependency with "mix deps.compile hexate --force", 
update it with "mix deps.update hexate" or clean it with "mix deps.clean hexate"
```
I've tried the "usual" way of getting around this but didn't work: `{:hexate, "~> 0.6.1", manager: :rebar3, override: true}`

Fortunately `fnv`'s head commit in main branch includes [the commit](https://github.com/asaaki/fnv.ex/commit/8bcce7248095361228b7e50e6123e8fc2f73337e) that removes the dependency 'hexate'.

## Proposal

`mix.exs` dependency to pull from head of `fnv` library, perhaps locked to a SHA for safety:

`{:fnv, github: "asaaki/fnv.ex", ref: "d7c55d3d8ce8046fe30e591cee59d6beb883012f"}`

Or, try to see if 32bit version of FNA hash would suffice, and switch the FNV library to [fnv1a](https://github.com/jeremytregunna/fnv1a)

**Comment by btkostner** [comment]
I haven’t looked at the library weight, but we might be able to copy it into the project and avoid the dependency all together
